title: BAIAI
description: The homepage of BAIAI
url: https://baiai.github.io
avatar: /assets/img/avatar.jpeg
paginate: 10
permalink: pretty
cover_image: /assets/img/cover.jpeg
timezone: +0000

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      layout: "post"
      author: "BAIAI"
      image: "assets/img/avatar.jpeg"
      share: true
  - scope:
      path: ""      
      type: "pages"
    values:
      layout: "page"
      author: "BAIAI"
      image: "assets/img/avatar.jpeg"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

include:
  - _pages
  
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts/

# Optimize Jekyl SEO Tag
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: UA-179353572-1

# Replace this value and uncomment to enable Disqus
disqus: vszhub

# Specify the author for blog posts
remote_theme: vszhub/not-pure-poole
